### ISSUE TITLE
PT no longer works on iOS 9.3.5

### ISSUE THREAD

**Issue by ofheroes** [taniman/pt-settings#4]
Until a few weeks ago I used PT on my iPad mini, iOS 9.3.5. But after installing the latest PT version (2.1.10) it no longer works. Is iOS 9.3.5 no longer supported by pT?

**Comment by taniman** [comment]
This is not the place for reporting possible issues with the bot. 
Please created your issue at the proper place
https://github.com/taniman/profit-trailer with correct description
